name: workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: last stage
        run: echo "thank you all - bye!"
      - name: last stage
        run: echo "thank you all - bye!"
      - name: checkout
        run: echo "checkout the code again - bye!"
 second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: last stage
        run: echo "thank you all - bye!"
      - name: last stage
        run: echo "thank you all - bye!"
      - name: checkout
        run: echo "checkout the code again - bye!"

